- name: configure shell
  hosts: "*"
  tasks:
    - name: Fetch starship
      get_url:
        url: https://starship.rs/install.sh
        dest: /tmp

    - name: Run starship installer
      ansible.builtin.shell:
          cmd: sudo sh /tmp/install.sh --yes
    
    - name: Update bashrc for starship for robin user
      lineinfile:
        dest: /home/robin/.bashrc
        line: eval "$(starship init bash)"
        owner: robin
      
    - name: Creates config directory
      file:
        path: ~/.config
        state: directory
    
    - name: Copy starship.toml
      ansible.builtin.copy:
        src: ~/.config/starship.toml
        dest: ~/.config/starship.toml
        remote_src: false
        owner: robin
        group: robin
        mode: '0644'
